### ISSUE TITLE
haxelib binary doesn't seem to work on macOS

### ISSUE THREAD

**Issue by jwir3** [HaxeFoundation/npm-haxe#13]
My setup:
  **Machine**: Macbook Pro, Late 2016 Edition
  **OS**: Mac OS Sierra 10.12.3
  **Npm Version**: 5.3.0 (although I've tried it with multiple versions, and this is my current/latest)
  **Dependencies/Package.json**:
```
  "devDependencies": {
    "browserify": "^14.4.0",
    "decomment": "^0.9.0",
    "dom-parser": "^0.1.5",
    "find-parent-dir": "^0.3.0",
    "haxe": "github:clemos/npm-haxe#3.3.0-rc.1",
    "rimraf": "^2.5.4",
    "stackblur-canvas": "^1.4.0",
    "uglify-js": "2.7.5",
    "xml2js": "*"
  }
```

When I attempt to run the following script:
```
"scripts": {
    "docs": "HAXELIB_ENABLE_NEKO=1 haxelib run dox -i dist -o dist/docs",
  },
```

or, if I attempt to run `./node_modules/haxe/bin/haxelib run dox -i dist -o dist/docs` (or any `haxelib` command), I receive the following: 

```
Type not found : haxelib.client.Main
```

However, if I run the manually-installed haxelib binary (from the package installed from haxe.org, which is what I use for my 'global' haxe installation), I have the following experience:
```
$ haxelib
Haxe Library Manager 3.3.0 - (c)2006-2016 Haxe Foundation
  Usage: haxelib [command] [options]
  Basic
    install   : install a given library, or all libraries from a hxml file
    update    : update a single library (if given) or all installed libraries
    remove    : remove a given library/version
    list      : list all installed libraries
    set       : set the current version for a library
  Information
    search    : list libraries matching a word
    info      : list information on a given library
    user      : list information on a given user
    config    : print the repository path
    path      : give paths to libraries
    version   : print the currently using haxelib version
    help      : display this list of options
  Development
    submit    : submit or update a library package
    register  : register a new user
    dev       : set the development directory for a given library
    git       : use Git repository as library
    hg        : use Mercurial (hg) repository as library
  Miscellaneous
    setup     : set the haxelib repository path
    newrepo   : create a new local repository
    deleterepo: delete the local repository
    convertxml: convert haxelib.xml file to haxelib.json
    run       : run the specified library with parameters
    proxy     : setup the Http proxy
  Available switches
    --flat    : do not use --recursive cloning for git
    --always  : answer all questions with yes
    --debug   : run in debug mode, imply not --quiet
    --quiet   : print less messages, imply not --debug
    --system  : run bundled haxelib version instead of latest update
    --never   : answer all questions with no
    --global  : force global repo if a local one exists
```

Running the dox command with the globally-installed haxelib binary works as expected, so it seems as though something is incorrect with the npm-installed version.

**Comment by clemos** [comment]
I've upgraded the `3.3.0-rc.1` tag to add support for `HAXELIB_ENABLE_NEKO` (it was added later), so it should work now (given you have `neko` installed).
Another related problem is that Mac and Windows archives miss the `extra` folder, and thus don't contain `haxelib` sources, which are needed to run `haxelib` via the interpreter... 
I'll probably have to download `haxelib` sources separately like I used to do to solve this :|

**Comment by jwir3** [comment]
Is there a way to install neko using npm? The reason I ask is that it would be nice to have everything self-contained within NPM, so the clients of our library (who aren't familiar with haxe and it's installation nuances), and all they have to do is `npm i`, followed by an `npm run build`.

**Comment by clemos** [comment]
No, there is currently no way to install `neko` via `npm`.
I think Neko is a bit more difficult to package to npm, as it requires globally installing files such as `libneko`.
That's why I tried to make `npm-haxe` to work as much as possible without neko in the first place.
Regarding your case, I think it would be easier for you to distribute a pre-compiled version of your lib, so people who want to use it don't need to install neko + haxe + dox.

**Comment by damoebius** [comment]
https://github.com/HaxeFoundation/npm-haxe/issues/7

**Comment by damoebius** [comment]
#7

**Comment by damoebius** [comment]
See #7 
Neko is now available on the beta channel
