### ISSUE TITLE
Binaries caching?

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/npm-haxe#16]
I understand this npm module downloads the right binary for your platform - is there any caching strategy? In CI scenarios, without caching I'm anticipating that every clean build will download the binaries - in our Docker CI we heavily depend on npm cache and usually do clean builds.

Apparently npm has a mechanism to cache data (in the general `.npm` cache):
https://www.npmjs.com/package/cacache

**Comment by damoebius** [comment]
Hop, can you try this version : https://github.com/HaxeFoundation/npm-haxe/tree/feature/add-cache ?

**Comment by damoebius** [comment]
or npm install haxe@4.1.2 on the beta channel
