### ISSUE TITLE
Downloads Resources over HTTP

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/npm-haxe#22]
The latest version of NPM includes security auditing by default upon `npm install` and manually under `npm audit`, and `haxe` triggers a high severity warning:

```
                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  High            Downloads Resources over HTTP

  Package         haxe

  Patched in      No patch available

  Dependency of   haxe [dev]

  Path            haxe

  More info       https://nodesecurity.io/advisories/177


[!] 1 vulnerability found - Packages audited: 17806 (17803 dev, 266 optional)
    Severity: 1 High
```

Is there a place to download the Haxe packages that is HTTPS, instead of HTTP?

**Comment by jgranick** [comment]
Github started marking these, too

![image](https://user-images.githubusercontent.com/833997/40814686-95b419fc-64f6-11e8-8af3-55ff45ea8877.png)

**Comment by damoebius** [comment]
@andyli i can't use hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/ in HTTPS
Is there a place to download the Haxe packages that is HTTPS ?

**Comment by damoebius** [comment]
Thank you @andyli 
@jgranick should be ok with 5.0.10. Can you confirm it ?

**Comment by jgranick** [comment]
The `npm audit` command still returns that it has the same vulnerability, but after reading further it appears that the "auditory database may be updated at any time" which leaves me wondering when it should be refreshed? Presumably the new version does fix it, but it's hard to know for sure when/if it will clear their system 🙁
