### ISSUE TITLE
npm i gets stuck

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/npm-haxe#28]
when running 
```npm i```
It seems like it will get stuck one of the lib sometimes.
There is no error message, but yeah it just doesn't progress, this coupled with that fact that after the initial install the only way to update the libs is to completely delete the node_modules I'm finding it almost impossible to get my libs installed.

**Comment by peteshand** [comment]
Still not 100% what the issue is, but it may have to do with lib versions.
Are there any error messaging that could be piped out when this type of problems?

**Comment by peteshand** [comment]
A fix for this has been added to the following pull request: https://github.com/HaxeFoundation/npm-haxe/pull/29

**Comment by damoebius** [comment]
Hey,
I published a new release on NPM, haxe 5.1.1 with your PR
Can you test it ?

**Comment by peteshand** [comment]
Hey @damoebius. Thanks.

Just tested and it's working as expected.

I am having some issues on Windows, however this is a completely different issue.. Tho if you have a minutes let me know if you've seen the error before: https://github.com/openfl/lime/issues/1348
I have a feeling it's related more to lime or neko though.

**Comment by damoebius** [comment]
Ouch, sorry i don't know what's going wrong with lime.

**Comment by peteshand** [comment]
👍
