### ISSUE TITLE
Unsupported platform for haxe@5.2.1 for M1 Ventura

### ISSUE THREAD

**Issue by Beraliv** [HaxeFoundation/npm-haxe#36]
**What**

In private project there's a dependency that has `haxe`. When I run:

```bash
npm i
```

I see the following error:

```bash
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for haxe@5.2.1: wanted {"os":"win32,win64,darwin,linux","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    win32,win64,darwin,linux
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexey.berezin/.npm/_logs/2023-03-01T12_33_41_606Z-debug.log
```

My colleagues with the same setup don't have this error (at least 2 people)

**Reproduction**

I've created a small project where I see the same behaviour – https://github.com/Beraliv/haxe-example

Let me know if I need to share any additional information

I've mistaken by creating issue in https://github.com/HaxeFoundation/haxe/issues/10989 in the first place

**Comment by GM-Alex** [comment]
Since haxe provides linux-arm64 builds at https://build.haxe.org/ wouldn't it not enough to adjust the haxe-url.js and package.json? Is here any solution planned? Shouldn't not that hard, or I'm wrong? I'm wondering why this issue is this long open.

**Comment by Beraliv** [comment]
For the benefit of others, I ran `brew install pkg-config cairo pango libpng jpeg giflib librsvg`, then installed package with `npm i` and it worked

If it still doesn't work, you may need to force installing the specific version, in my case it was `npm install haxe@5.2.1 -f`

Hope it helps others

I'm also happy to close this issue as it's not a problem for me anymore

**Comment by GM-Alex** [comment]
@Beraliv This won't help if you try to run it within a docker container.

**Comment by Beraliv** [comment]
> @Beraliv This won't help if you try to run it within a docker container.

Please create another issue and reference this one as this issue was specifically about running it on M1 Ventura
