### ISSUE TITLE
Clarify neko dependency

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/npm-haxe#7]
While neko is not required for "basic" use-cases (`-lib`, `haxelib install ...`, ...), the README mentions it's still needed for `haxelib run ...`.
From what I understand, `haxelib`, when run by the Haxe interpreter, still has a few minor limitations regarding SemVer (?)

In any case, it might be worth : 
- Adding a warning message in the wrapper, in case the user runs into errors with `haxelib run ...`.
- Creating a `neko` npm package ?

**Comment by damoebius** [comment]
According to this discution : https://community.haxe.org/t/support-haxe-on-npm/291/14?u=damoebius
Neko is now available with 
```shell
npm install haxe@4.1.3
```
