### ISSUE TITLE
Intellij Idea configuration

### ISSUE THREAD

**Issue by dmouton** [HaxeFoundation/npm-haxe#8]
How to configure intellij with the new module ?

I create a new Haxe SDK, targeting node_modules\haxe\current [OK]
While compiling i a have unknown error
```
Error:compilation failed
Warning:Not_found
```

With the -v compiler option i get this :

Warning:Classpath : C:/Projects/David/developpement/haxe/taminahx/node_modules/createjs-haxe/;
C:/Projects/David/developpement/haxe/taminahx/node_modules/msignal/;
C:/Projects/David/developpement/haxe/taminahx/node_modules/mconsole-npm/;
C:/Projects/David/developpement/haxe/taminahx/src/;
**C:\Projects\Happy\SakuraHx\heidi\node_modules\taminahx\node_modules\haxe\bin/../std/js/_std/;
C:\Projects\Happy\SakuraHx\heidi\node_modules\taminahx\node_modules\haxe\bin/../std/**

It seems that the too last lines are from my HAXE_STD_PATH environnement variable

The previous module manage this variable during the installation
https://github.com/damoebius/haxe-npm/blob/master/bin/haxe-cli.js

**Comment by clemos** [comment]
The new package also sets this var in the env where haxe is run : 
https://github.com/HaxeFoundation/npm-haxe/blob/master/lib/vars.js#L17
But you have to execute `haxe` from `node_modules/haxe/bin/haxe` or `node_modules/.bin/haxe` (same for `haxelib`), not from `node_modules/haxe/current` (which is just the content of the archive)

So you may try to setup Haxe SDK in `node_modules/haxe/bin/`

**Comment by dmouton** [comment]
Intellij doesn't want it
It force me to choose a 'valid' SDK folder like node_modules\haxe\current
I can't define the haxe exec path

**Comment by clemos** [comment]
I don't know how IntellJ validates this SDK folder.
Maybe you can try and copy `current/std` into `bin/` and select `current/bin/` again, 
to see if it requires the presence of a `std` directory.
Otherwise, we could dig into their code to see what changes are needed in order for the plugin to consider the `bin` directory as a valid SDK...

**Comment by clemos** [comment]
*edit `current/bin` => `bin/`

**Comment by dmouton** [comment]
Well after some test i'm pretty sure that it just look for 'haxe.exe'

**Comment by clemos** [comment]
Ok so it's just a matter of renamining `bin/haxe` to `bin/haxe.exe` ?

**Comment by dmouton** [comment]
Mmm it could be as simple as this, but i think Intellij will try to run it
like a windows executable and i don't know if it'll work with a js script



*David Mouton--*
Directeur Technique @Happy-Technologies
Tél : 05.57.26.61.00
Mob. : 06.12.63.58.15

2016-03-22 16:09 GMT+01:00 Clément Charmet <notifications@github.com>:

**Comment by clemos** [comment]
It seems NPM should create `.cmd` wrappers for `bin` scripts, but I don't know where it places these wrappers, or if they are only created when installing globally...
(see https://github.com/ForbesLindesay/cmd-shim)

**Comment by clemos** [comment]
Any news about that ?

**Comment by damoebius** [comment]
Not really, i updated manually my HAXE_STD_PATH environnement variable to have Intellij working.
Maybe we can ask TiVO guys for help ?

**Comment by clemos** [comment]
Yes, it might be nice to open an issue on https://github.com/JetBrains/intellij-haxe to ask them what are the requirements for the SDK path to be valid.

**Comment by damoebius** [comment]
On a new installation i can't configure Intellij to work with the new npm module.

> Warning:Standard library not found

I tried `export HAXE_STD_PATH=/usr/local/lib/node_modules/haxe/current/std
`
But with -v, Intellij still looking in other folder

> Warning:Classpath : /home/david/Public/taminahx/node_modules/createjs-haxe/;/home/david/Public/taminahx/node_modules/msignal/;/home/david/Public/taminahx/node_modules/mconsole-npm/;/home/david/Public/taminahx/src/;/usr/lib/haxe/extraLibs/;/usr/local/lib/haxe/extraLibs/;;/usr/lib/haxe/std/js/_std/;/usr/share/haxe/std/js/_std/;/usr/local/lib/haxe/std/js/_std/;/usr/lib/haxe/std/;/usr/share/haxe/std/;/usr/local/lib/haxe/std/

**Comment by andyli** [comment]
I've moved the folder. Would you try
```
export HAXE_STD_PATH=/usr/local/lib/node_modules/haxe/downloads/haxe/std 
```

**Comment by damoebius** [comment]
It's not my problem.
Intellij is looking into wrong folders. 
I edit my .profile and .bashrc, and /etc/environnement but it still doesn't work :(

**Comment by damoebius** [comment]
Mmm...
I edit also /etc/profile and /etc/bashrc without any effect.
I reboot my computer and ... it works.
I don't know why it is working now :/

**Comment by EBatTiVo** [comment]
> I reboot my computer and ... it works.

Forgive me if this is incorrect, but it sounds like you misunderstand how environment variables work: they don't change when you edit the script; they change when that script is run.  Therefore, when you edit ```.bashrc``` or the related global scripts, you must either "source" them (e.g. ```$ source .bashrc```, which runs ```.bashrc``` in the current shell) or start a new bash shell (which is one thing that rebooting does).

At any rate, the intellij-haxe plugin never runs 'haxe.exe' (or 'haxe', depending upon your envronment).  It runs ```neko``` or ```lime``` build tools to compile.  It expects those tools to run the compiler as appropriate.  The locations of the neko and lime executables are specified in IDEA via the 'haxe' tab in module settings (it's project global, though, not specific to the module).  As a side note, the plugin also uses ```haxelib``` to find libraries and auto-add them to your (intellij) project

**Comment by damoebius** [comment]
Agree, i completly misunderstand how environment variables work. But when i configure my Haxe SDK, and i choose another std path, it's hard to understand why intellij still use another folder.

**Comment by EBatTiVo** [comment]
I'll bet that you start IntelliJ IDEA using an icon on a GUI desktop, in which case, IDEA is getting the environment (including variables) that was set up when the desktop was started.

Here are the concepts you need to understand (you should research these):
 - That environment variables are local the the program being worked on.  They can be passed to child processes, but not to parents or siblings.
 - ```bash``` has several configuration files that affect how the variables are set up (globally and per user), and variables that are to be passed to children must be ```export```ed or they aren't inherited.  It also plenty of arcana about how sub-processes are created that affect the environment.  ```sudo```, if you use it, also affects them.
 - The GUI and command lines are fundamentally different things, running in different process trees, though command lines running in a GUI are in the GUI's process tree.  If a process is already running, changing things in one doesn't affect the other.  That said, there are some common configuration files that are read by both bash and your GUI (I think ```/etc/profile``` and ```~/.bashrc```, but each version of Linux seems to have its own custom scripts, too).

**Comment by damoebius** [comment]
Thank you, i got it. 
BTW i think that intellij should use my intellij SDK configuration to compile.

@clemos do you think that we can do something ?
