### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/npm-haxe#9]
Maybe it's time to release the package on npmjs.org/haxe, now ?
How can I help ?

**Comment by damoebius** [comment]
Agree.
I didn't try haxelib support but all our projects run now with 4.0.0 and it works well.
A release before wwx is a good thing ;)
Can you do it ?

**Comment by andyli** [comment]
I'm not against doing a release, but I would like to wait for some time before mentioning it in the haxe.org download page. The reason is that I still think we should package Neko too, but Neko 2.0 has several problems which will be fixed in the next release.

**Comment by clemos** [comment]
IMHO, `neko` should be in a separate `npm` package, linked via [optional dependencies](https://docs.npmjs.com/files/package.json#optionaldependencies).
In any case, I would be in favor of releasing the current version beforehand.

**Comment by andyli** [comment]
Yes, I agree. Feel free to make a release to npm :)

**Comment by statianzo** [comment]
Any status updates on this?

**Comment by damoebius** [comment]
On neko ?

**Comment by clemos** [comment]
I've switched back to my [personal version](https://github.com/clemos/npm-haxe) shortly after transferring ownership to HF because of a minor issue, 
and updated it to haxe 3.3 rc1, which was not trivial due to extracted directory and archive name mismatch (see https://github.com/clemos/npm-haxe/pull/1)
If I have some time, I'll merge with this official version and test it.
In the meantime, you may want to review the few open issues and either update or close them ?
